# Use Node.js 20 (matching your CI/CD)
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app

# Copy package files
COPY package.json yarn.lock ./
# Install dependencies with frozen lockfile
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the Next.js app
# Accept build arguments for NEXT_PUBLIC_* variables
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_BASE_URL_PROD
ARG NEXT_PUBLIC_BASE_URL_UAT
ARG NEXT_PUBLIC_ENV
ARG NEXT_PUBLIC_ENABLE_COHORT
ARG NEXT_PUBLIC_COHORT_URL_PROD
ARG NEXT_PUBLIC_COHORT_URL_UAT
ARG NEXT_PUBLIC_EVENT_URL_PROD
ARG NEXT_PUBLIC_EVENT_URL_UAT
ARG NEXT_PUBLIC_SYSTEM_PROPERTIES_URL
ARG NEXT_PUBLIC_ENABLE_PERMISSION
ARG NEXT_PUBLIC_PERMISSION_S3_URL
ARG NEXT_PUBLIC_ORGANIZATIONS_ENABLE_TENANT
ARG NEXT_PUBLIC_ORGANIZATIONS

# Set environment variables for build
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
ENV NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}
ENV NEXT_PUBLIC_BASE_URL_PROD=${NEXT_PUBLIC_BASE_URL_PROD}
ENV NEXT_PUBLIC_BASE_URL_UAT=${NEXT_PUBLIC_BASE_URL_UAT}
ENV NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
ENV NEXT_PUBLIC_ENABLE_COHORT=${NEXT_PUBLIC_ENABLE_COHORT}
ENV NEXT_PUBLIC_COHORT_URL_PROD=${NEXT_PUBLIC_COHORT_URL_PROD}
ENV NEXT_PUBLIC_COHORT_URL_UAT=${NEXT_PUBLIC_COHORT_URL_UAT}
ENV NEXT_PUBLIC_EVENT_URL_PROD=${NEXT_PUBLIC_EVENT_URL_PROD}
ENV NEXT_PUBLIC_EVENT_URL_UAT=${NEXT_PUBLIC_EVENT_URL_UAT}
ENV NEXT_PUBLIC_SYSTEM_PROPERTIES_URL=${NEXT_PUBLIC_SYSTEM_PROPERTIES_URL}
ENV NEXT_PUBLIC_ENABLE_PERMISSION=${NEXT_PUBLIC_ENABLE_PERMISSION}
ENV NEXT_PUBLIC_PERMISSION_S3_URL=${NEXT_PUBLIC_PERMISSION_S3_URL}
ENV NEXT_PUBLIC_ORGANIZATIONS_ENABLE_TENANT=${NEXT_PUBLIC_ORGANIZATIONS_ENABLE_TENANT}
ENV NEXT_PUBLIC_ORGANIZATIONS=${NEXT_PUBLIC_ORGANIZATIONS}
ENV NEXT_TELEMETRY_DISABLED=1

RUN yarn build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

# Expose port 3000
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the application
CMD ["node", "server.js"]

