export const AuthLabels = {
  flash: "Flash",
  login: "Login",
  email: "Email",
  password: "Password",
  signIn: "Sign In",
  signUp: "Sign Up",
  dashboard: "Dashboard",
  newTemplate: "Template",
  signInWith: "Sign in with",
  signInWithGoogle: "Sign in with Google",
  signInWithFacebook: "Sign in with Facebook",
  googleSignIn: "Google Sign In - Coming Soon",
  facebookSignIn: "Facebook Sign In - Coming Soon",
  welcomeBack: "Welcome to Flash ",
  signInToYourAccount: "Sign in to your account",
  dontHaveAnAccount: "Don't have an account?",
  signUpNow: "Sign up now",
  alreadyHaveAnAccount: "Already have an account?",
  orContinueWith: "Or continue with",
  emailAddress: "Email address",
  forgotPassword: "Forgot password?",
  createAnAccount: "Create an account",
  signUpToGetStarted: "Sign up to get started",
  confirmPassword: "Confirm Password",
  getStarted: "Get Started",
  learnMore: "Learn More",
  whyChooseFlash: "Why Choose Flash?",
  dynamicUiUpdatesWithoutAppStoreSubmissions:
    "Dynamic UI updates without app submissions",
  instantlyDeployUiChangesAcrossAllPlatforms:
    "Instantly UI changes across all platforms",
  oneConfigurationForAllYourPlatforms:
    "One configuration for all your platforms",
  readyToTransformYourMobileApp: "Ready to Transform Your Mobile App?",
  startBuildingNow: "Start Building Now",
  copyright: "© 2025 Flash. All rights reserved.",
  privacyPolicy: "Privacy Policy",
  termsOfService: "Terms of Service",
  joinThousandsOfDevelopersUsingFlashToBuildBetterMobileExperiences:
    "Join thousands of developers using Flash to build better mobile experiences.",
  flashHelpsYouBuildDynamicFlexibleMobileApplications:
    "Flash helps you build dynamic, flexible mobile applications. Update your app instantly without <s>app</s> submissions.",
  logout: "Log out",
  goToDashboard: "Go to Dashboard",
  transformYourAppWith: "Transform Your App with ",
};
