export const previewPanelStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  title: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "text.primary",
  },
  phoneMockup: {
    width: "100%",
    maxWidth: "300px",
    aspectRatio: "9/16",
    bgcolor: "#1a1a1a",
    borderRadius: "24px",
    p: 2,
    boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
  },
  phoneScreen: {
    width: "100%",
    height: "100%",
    bgcolor: "#000",
    borderRadius: "16px",
    overflow: "hidden",
    position: "relative",
  },
  contentArea: {
    width: "100%",
    height: "100%",
    p: 2,
    display: "flex",
    flexDirection: "column",
    gap: 1,
    overflow: "auto",
  },
  emptyState: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "text.secondary",
  },
  textContent: {
    color: "#fff",
    fontSize: "0.875rem",
  },
  imagePlaceholder: {
    width: "100%",
    minHeight: "100px",
    bgcolor: "rgba(255,255,255,0.1)",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "text.secondary",
  },
};
